apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
  - ../../base
configMapGenerator:
  - name: site-config
    behavior: replace
    literals:
      - SITE_NAME="My Static Website"
secretGenerator:
  - name: site-secret
    behavior: replace
    literals:
      - SECRET_KEY="super-secret-value"
