apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-app
          image: tejirih/kustomize-site:latest
          env:
            - name: ENV
              value: "staging"
