name: Deploy Static Website

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
        - kustomize-static-site/**  # Run only when files in 'kustomize-static-site' change

  pull_request:
    branches:
      - main
    paths:
        - kustomize-static-site/**  # Run for PRs affecting 'kustomize-static-site'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Update Kubeconfig
        run: |
          echo "Updating kubeconfig for EKS cluster..."
          aws eks update-kubeconfig --name kustomize-demo --region eu-north-1

      - name: Check current directory
        run: |
          pwd
          ls

      - name: Deploy to EKS with Kustomize
        run: |
          # Debug: Check the directory structure
          pwd
          ls -R  # List all files and directories recursively
          cd ./kustomize-static-site
          ls  # List files inside kustomize-static-site
          echo "Deploying application using Kustomize..."
          kubectl apply -k ./overlays/prod

