name: Kustomize CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - kustomize-capstone/**  # Run only when files in 'kustomize-capstone' change

  pull_request:
    branches:
      - main
    paths:
      - kustomize-capstone/**  # Run for PRs affecting 'kustomize-capstone'
    tags:
      - '*'  # This was incorrectly indented under 'push'
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./kustomize-capstone
        run: |
          ls
          ls -R
          docker build -t my-app .
          docker tag my-app tejirih/my-app:${{ github.sha }} 
          docker tag my-app tejirih/my-app:latest

      - name: Push Docker image
        run: |
          docker push tejirih/my-app:${{ github.sha }}
          docker push tejirih/my-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Replace with your AWS region

      - name: Update Kubeconfig for EKS Cluster
        run: aws eks update-kubeconfig --name kustomize-capstone --region eu-north-1

      - name: Deploy to Kubernetes (using Kustomize)
        working-directory: ./kustomize-capstone
        run: |
          kubectl apply -k kustomize/overlays/dev
