name: tests & Tag

on:
  push:
    branches:
      - main  # Run for every push to the main branch
    #paths:
      #- DevOps_Projects/GitAction_workaround  # This will run the workflow only when files inside 'your-folder' are changed
  pull_request:
    branches:
      - main
    #paths:
     # - DevOps_Projects/GitAction_workaround  # This will run the workflow for pull requests that affect 'your-folder'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Matrix build for different Node.js versions

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

            # Change to the correct directory
      - name: Change to the correct directory
        run: cd GitAction_workaround

      - name: checking contents
        run: ls
        
      # Step 2: Set up Node.js for the matrix build
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache node modules to speed up workflow
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Upgrade npm 10.9.0
        run: npm install -g npm@10.9.0
        
      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install
        working-directory: /home/runner/work/DevOps_Projects/DevOps_Projects/GitAction_workaround

      # Step 5: Run ESLint
     # - name: Run ESLint
       # run: |
        #  npm run lint  # Assumes you have a lint script defined in package.json

      # Step 6: Run Jest tests
      
      - name: Fix permissions for Jest executable
        run: chmod +x ./GitAction_workaround/node_modules/.bin/jest
        
      - name: location
        run: pwd

     # - name: checking permission
        # run: |
        #   ls -latr ./GitAction_workaround
        #   ls -latr ./GitAction_workaround/node_modules
        #   ls -latr ./GitAction_workaround/node_modules/.bin
        
        
      - name: Run Jest tests
        run: |
          npm test  # Assumes you have a test script defined in package.json
        working-directory: ./GitAction_workaround

  create-tag:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure this job runs after the tests pass
    if: github.ref == 'refs/heads/main'  # Runs only on push to main branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Create a semantic version tag
      - name: Create semantic version tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd GitAction_workaround  # Navigate to the directory containing package.json
          VERSION=$(npm version patch -m "Release version %s")  # Increment patch version and create tag
          echo "Created version: $VERSION"
          git config user.name "GitHub Actions"  # Configure git user
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git pull origin main
          git add package.json package-lock.json
          git commit -am "chore: release $VERSION"  # Commit version bump changes
          git push origin HEAD  # Push branch changes
          git tag # Debug: list all tags to verify creation
          git fetch --tags  # Fetch all tags to ensure synchronization
          git push origin $VERSION  # Push the new tag explicitly

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ./GitAction_workaround/*  # Specify files you want to include in the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available in GitHub Actions


