name: tests & Tag

on:
  push:
    branches:
      - main  # Run for every push to the main branch
    #paths:
      #- DevOps_Projects/GitAction_workaround  # This will run the workflow only when files inside 'your-folder' are changed
  pull_request:
    branches:
      - main
    #paths:
     # - DevOps_Projects/GitAction_workaround  # This will run the workflow for pull requests that affect 'your-folder'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Matrix build for different Node.js versions

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

            # Change to the correct directory
      - name: Change to the correct directory
        run: cd DevOps_Projects/GitAction_workaround
        
      # Step 2: Set up Node.js for the matrix build
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache node modules to speed up workflow
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 5: Run ESLint
     # - name: Run ESLint
       # run: |
        #  npm run lint  # Assumes you have a lint script defined in package.json

      # Step 6: Run Jest tests
      - name: Run Jest tests
        run: |
          npm test  # Assumes you have a test script defined in package.json

  create-tag:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure this job runs after the tests pass
    if: github.ref == 'refs/heads/main'  # Runs only on push to main branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Create a semantic version tag
      - name: Create semantic version tag
        id: create_tag
        run: |
          VERSION=$(npm version patch -m "Release version %s")  # Increment patch version
          echo "Created version: $VERSION"
          git push origin $VERSION

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: DevOps_Projects/GitAction_workaround/*  # Specify files you want to include in the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available in GitHub Actions


