name: Tests & Tag

on:
  push:
    branches:
      - main  # Run for every push to the main branch
    tags:
      - '*'  # Trigger on all tag pushes
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Test with Node.js version 18.x

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Change directory to the project folder
      - name: Change to the correct directory
        run: cd GitAction_workaround

      # Step 3: List contents for debugging
      - name: Check contents
        run: ls

      # Step 4: Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 5: Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Step 6: Upgrade npm
      - name: Upgrade npm to 10.9.0
        run: npm install -g npm@10.9.0

      # Step 7: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./GitAction_workaround

      # Step 8: Fix permissions for Jest
      - name: Fix permissions for Jest
        run: chmod +x ./GitAction_workaround/node_modules/.bin/jest

      # Step 9: Run Jest tests
      - name: Run Jest tests
        run: npm test
        working-directory: ./GitAction_workaround

  create-tag:
    runs-on: ubuntu-latest
    needs: build-and-test  # Run after build-and-test job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create semantic version Tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd GitAction_workaround
          git pull origin main --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest existing tag: $LATEST_TAG"
          NEW_VERSION=$(npm version patch -m "Release version %s")
          echo "New version created by npm: $NEW_VERSION"
          NEW_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ "$NEW_TAG" != "$NEW_VERSION" ]; then
            echo "Tag not found in git; creating manually..."
            git tag "$NEW_VERSION"
          fi
          echo "Local tags after npm version increment:"
          git tag
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add package.json package-lock.json
          git commit -m "chore: release $NEW_VERSION"
          git push origin HEAD
          git push origin "$NEW_VERSION"
          git push origin --tags
          git fetch --tags
          echo "tag_name=$NEW_VERSION" >> $GITHUB_ENV

  create-release:
    runs-on: ubuntu-latest
    needs: create-tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch tags (ensure)
        run: |
          git fetch --tags
          git tag

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
