name: E-Commerce App CI

on:
  push:
    branches:
      - main
   # paths:
    #  - 'ecommerce/**'  # Trigger on push to any file inside the ecommerce folder
  pull_request:
    branches:
      - main
   # paths:
    #  - 'ecommerce/**'  # Trigger on pull requests affecting the ecommerce folder

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Testing with multiple Node versions

    steps:
    # Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - name: Location
      working-directory: ./ecommerce/api
      run: |
        pwd
        ls

    # Install dependencies for the API and Webapp
    - name: Install API dependencies
      working-directory: ./ecommerce/api
      run: |
        pwd
        ls
        npm install

    - name: Install Webapp dependencies
      working-directory: ./ecommerce/webapp
      run: |
        npm install

    - name: Fix permissions for Jest executable
      run: |
        chmod +x ./ecommerce/api/node_modules/.bin/jest
        chmod +x ./ecommerce/webapp/node_modules/.bin/jest

    # Run ESLint in the API
    # - name: Run ESLint for API
    #   working-directory: ./ecommerce/api
    #   run: |
    #     npx eslint . --ext .js

    # # Run ESLint in the Webapp
    # - name: Run ESLint for Webapp
    #   working-directory: ./ecommerce/webapp
    #   run: |
    #     npx eslint . --ext .js,.jsx

    # Run Jest tests for the API
    - name: Run Jest tests for API
      working-directory: ./ecommerce/api
      run: |
        npm test -- --coverage --maxWorkers=2

    # Run Jest tests for the Webapp
    - name: Run Jest tests for Webapp
      working-directory: ./ecommerce/webapp
      run: |
        npm test -- --coverage --maxWorkers=2

    # Build the Webapp (optional, depending on your setup)
    - name: Build Webapp
      working-directory: ./ecommerce/webapp
      run: |
        npm run build
